export const dummyData = {
  courses: [],
  instructor: {},
  selectedCourse: {
    id: 100000,
    course_id: 1000000,
    size: 12,
    description: 'Welcome to Python!',
    subject: 'Please select a course!',
    start_time: '',
    start_date: 'more - info',
    end_date: '11-19-2021',
    end_time: 'here',
    location: 'https://zoom.us/my/haleyh',
  },
  own_programs: [
    {
      id: '1',
      subject: 'Python',
      other: '',
      description: '',
      prerequisite: '',
      classSize: '',
      age: '',
      session: '',
      duration: '',
      date: 'Monday',
      time: '17:00:00',
      status: 'Pending',
    },
    {
      id: '2',
      subject: 'Java',
      other: '',
      description: '',
      prerequisite: '',
      classSize: '',
      age: '',
      session: '',
      duration: '',
      date: 'Sunday',
      time: '17:00:00',
      status: 'Approved',
    },
  ],
  errorMessage: '',
  instructor_data: {
    instructor_id: 3,
    instructor_name: 'Jane Smith',
    user_id: 9,
    rating: 3,
    approved: true,
    approved_by: 1,
    instructor_bio: 'I love making content for people to enjoy!',
    inbox: [],
  },
  course_id: [3],
  course_schedule: [
    {
      session_id: 0,
      course_id: 3,
      size: 1,
      description: 'Welcome to Python!',
      subject: 'Intro to Python',
      start_time: '15:00:00',
      start_date: '2021-12-15T07:00:00.000Z',
      end_date: '2021-12-16T07:00:00.000Z',
      end_time: '17:00:00',
      location: 'https://zoom.us/my/haleyh', // host by coderheros
      prereq: 'None',
      // after the instructor apply to teach the course,
      // we will post instructor id to backend
    },
    {
      session_id: 0,
      course_id: 0,
      size: 12,
      description: 'Welcome to JavaScript!',
      subject: 'Intro to JavaScript',
      start_time: '17:00:00',
      start_date: '2022-10-10T07:00:00.000Z',
      end_date: '2022-10-10T07:00:00.000Z',
      end_time: '17:00:00',
      location: 'https://zoom.us/my/haleyh',
      prereq: 'JS 101',
    },
    {
      session_id: 0,
      course_id: 1,
      size: 1,
      description: 'Welcome to CSS!',
      subject: 'Intro to CSS',
      start_time: '17:00:00',
      start_date: '2022-10-10T07:00:00.000Z',
      end_date: '2022-10-10T07:00:00.000Z',
      end_time: '17:00:00',
      location: 'https://zoom.us/my/haleyh',
      prereq: 'None',
    },
  ],
  newsfeed: [],
  classes: [
    {
      class_name: 'App Building Fundamentals',
      class_description:
        'A month-long course where students with design, build, and deploy an app from beginning to end!',
      days_of_week: ['Monday'],
      max_size: 20,
      min_age: 7,
      max_age: 12,
      instructor_id: 1,
      program_id: 1,
      start_time: '08:00:00',
      end_time: '12:30:00',
      start_date: '04/04/2022',
      end_date: '04/28/2022',
      location: "Children's Coding Center",
      number_of_sessions: 4,
    },
    {
      class_name: 'Mindful Design',
      class_description:
        'Students will learn about creativity and web design basics',
      days_of_week: ['Wednesday', 'Friday'],
      max_size: 12,
      min_age: 6,
      max_age: 10,
      instructor_id: 2,
      program_id: 3,
      start_time: '15:30:00',
      end_time: '17:45:00',
      start_date: '04/04/2022',
      end_date: '04/28/2022',
      location: "Children's Coding Center",
      number_of_sessions: 8,
    },
  ],
};
