export const dummyData = {
  selectedCourse: {
    id: 100000,
    course_id: 1000000,
    size: 12,
    description: 'Welcome to Python!',
    subject: 'Please select a course!',
    start_time: '',
    start_date: 'more - info',
    end_date: '11-19-2021',
    end_time: 'here',
    location: 'https://zoom.us/my/haleyh',
  },
  instructor_id: 3,
  user_id: 9,
  rating: 3,
  approved: true,
  approved_by: 1,
  instructor_bio: 'I love making content for people to enjoy!',
  inbox: [],
  course_id: [3],
  course_schedule: [
    {
      id: 0,
      course_id: 3,
      size: 12,
      description: 'Welcome to Python!',
      subject: 'Intro to Python',
      start_time: '5:00pm',
      start_date: '11-10-2021',
      end_date: '11-10-2021',
      end_time: '6:00pm',
      location: 'https://zoom.us/my/haleyh',
    },
    {
      id: 1,
      course_id: 0,
      size: 12,
      description: 'Welcome to Python!',
      subject: 'Intro to JavaScript',
      start_time: '5:00pm',
      start_date: '11-19-2021',
      end_date: '11-19-2021',
      end_time: '6:00pm',
      location: 'https://zoom.us/my/haleyh',
    },
    {
      id: 2,
      course_id: 1,
      size: 12,
      description: 'Welcome to Python!',
      subject: 'Intro to CSS',
      start_time: '6:00pm',
      start_date: '11-19-2021',
      end_date: '11-19-2021',
      end_time: '7:00pm',
      location: 'https://zoom.us/my/haleyh',
    },
  ],
};
