export const parentDummyData = {
  parentProfile: {
    parent_id: 10,
    children: [
      { child_id: 1, child_name: 'Mark' },
      { child_id: 2, child_name: 'Shelly' },
      { child_id: 3, child_name: 'John' },
    ],
    bio: '',
  },

  cart: [],

  children: [
    { parent_id: 0, user_id: 3, username: 'Joannsson', age: 7 },
    { parent_id: 1, user_id: 4, username: 'Jordansdaughter', age: 9 },
    { parent_id: 1, user_id: 5, username: 'Jordansson', age: 12 },
  ],

  enrollments: [
    { child_id: 0, course_id: 0, completed: false },
    { child_id: 0, course_id: 0, completed: false },
    { child_id: 0, course_id: 0, completed: false },
  ],

  inbox: [{ user_id: 0 }, { user_id: 3 }, { user_id: 8 }],

  messages: [
    {
      sent_at: '2021/11/02T01:51:39+00:00',
      title: 'Help with Homework?',
      read: true,
      message: 'I need the answers to the assignment please.',
      inbox_id: 0,
      sender_id: 1,
    },
    {
      sent_at: '2021/11/02T01:51:39+00:00',
      title: "What's my grade?",
      read: true,
      message: 'Hey Ms. Teacher can you tell me my grade?',
      inbox_id: 0,
      sender_id: 1,
    },
    {
      sent_at: '2021/11/02T01:51:39+00:00',
      title: 'Going to need to cancel.',
      read: false,
      message: 'My child has to miss the class',
      inbox_id: 1,
      sender_id: 2,
    },
    {
      sent_at: '2021/11/02T01:51:39+00:00',
      title: 'Kid is sick',
      read: true,
      message: 'Can we get a refund for this class?',
      inbox_id: 2,
      sender_id: 3,
    },
    {
      sent_at: '2021/11/02T01:51:39+00:00',
      title: 'When is class?',
      read: false,
      message: 'I noticed the time was funky and had to ask.',
      inbox_id: 1,
      sender_id: 5,
    },
    {
      sent_at: '2021/11/02T01:51:39+00:00',
      title: 'Is this a yoga course?',
      read: false,
      message: 'How is yoga and coding taught together?',
      inbox_id: 3,
      sender_id: 7,
    },
    {
      sent_at: '2021/11/02T01:51:39+00:00',
      title: 'Where is my achievement?',
      read: false,
      message: "my achievement didn't pop up when I did class.",
      inbox_id: 0,
      sender_id: 1,
    },
  ],
  bookings: {
    isFetching: false,
    bookings: [
      {
        child_id: 2,
        child_name: 'Shelly',
        schedule_id: 1,
        course_id: 1,
        instructor_id: 1,
        instructor_name: 'Test003',
        size: 15,
        subject: 'CS101',
        description: 'Computer Science fundamentals',
        prereqs: null,
        start_date: '2021/05/30T07:00:00.000Z',
        end_date: '2022/10/10T07:00:00.000Z',
        start_time: '17:00:00',
        end_time: '18:00:00',
        location: 'https://zoom.us/my/john123',
      },
      {
        child_id: 12,
        child_name: 'Joe',
        schedule_id: 2,
        course_id: 3,
        instructor_id: 2,
        instructor_name: 'Test006',
        size: 16,
        subject: 'JavaScriptB',
        description: 'Intermediate JavaScript.',
        prereqs: ['JavaScriptA'],
        start_date: '2021/12/15T07:00:00.000Z',
        end_date: '2022/10/11T07:00:00.000Z',
        start_time: '15:00:00',
        end_time: '16:00:00',
        location: 'https://zoom.us/my/john321',
      },
      {
        child_id: 13,
        child_name: 'Mark',
        schedule_id: 1,
        course_id: 1,
        instructor_id: 1,
        instructor_name: 'Test003',
        size: 15,
        subject: 'CS101',
        description: 'Computer Science fundamentals',
        prereqs: null,
        start_date: '2021/12/22T07:00:00.000Z', // mm/dd/yyyy
        end_date: '2022/10/10T07:00:00.000Z',
        start_time: '17:00:00',
        end_time: '18:00:00',
        location: 'https://zoom.us/my/john123',
      },
      {
        child_id: 13,
        child_name: 'Mark',
        schedule_id: 2,
        course_id: 3,
        instructor_id: 2,
        instructor_name: 'Test006',
        size: 16,
        subject: 'JavaScriptB',
        description: 'Intermediate JavaScript.',
        prereqs: ['JavaScriptA'],
        start_date: '2021/12/20T07:00:00.000Z',
        end_date: '2022/10/11T07:00:00.000Z',
        start_time: '15:00:00',
        end_time: '16:00:00',
        location: 'https://zoom.us/my/john321',
      },
    ],
    error: '',
  },

  availableCourses: [
    {
      schedule_id: 0,
      course_id: 0,
      instructor_id: 1,
      instructor_name: 'Test007',
      size: 20,
      subject: 'App Building Fundamentals',
      description:
        'A month/long course where students with design, build, and deploy an app from beginning to end!',
      prereqs: [' JavaScript', 'HTML', 'CSS'],
      start_date: '12/04/2022',
      end_date: '12/28/2022',
      start_time: '08:00:00',
      end_time: '09:00:00',
      location: "Children's Coding Center",
      price: 1200,
    },

    {
      schedule_id: 0,
      course_id: 0,
      instructor_id: 2,
      instructor_name: 'Test013',
      size: 16,
      subject: 'App Building Fundamentals',
      description:
        'A month/long course where students with design, build, and deploy an app from beginning to end!',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '04/04/2022',
      end_date: '04/28/2022',
      start_time: '08:30:00',
      end_time: '09:30:00',
      location: 'https://zoom.us/my/john321',
      price: 800,
    },
    {
      schedule_id: 0,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test009',
      size: 14,
      subject: 'Welcome to Python!',
      description: 'Please select a course!',
      prereqs: ['javascript,css,html'],
      start_date: '10/07/2022',
      end_date: '11/06/2022',
      start_time: '09:00:00',
      end_time: '10:00:00',
      location: 'https://zoom.us/my/haleyh',
      price: 500,
    },
    {
      schedule_id: 1,
      course_id: 1,
      instructor_id: 3,
      instructor_name: 'Test011',
      size: 15,
      subject: 'JavaScriptB',
      description: 'Intermediate JavaScript.',
      prereqs: ['JavaScriptA'],
      start_date: '10/19/2022',
      end_date: '11/20/2022',
      start_time: '10:00:00',
      end_time: '11:00:00',
      location: 'https://zoom.us/my/john321',
      price: 1200,
    },
    {
      schedule_id: 0,
      course_id: 0,
      instructor_id: 2,
      instructor_name: 'Test013',
      size: 16,
      subject: 'Intro to HTML',
      description:
        ' A course where students with design, build, and deploy an app from beginning to end!',
      prereqs: [''],
      start_date: '03/05/2022',
      end_date: '03/25/2022',
      start_time: '13:00:00',
      end_time: '14:00:00',
      location: 'https://zoom.us/my/tommy',
      price: 450,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test006',
      size: 16,
      subject: 'JavaScriptB',
      description: 'Intermediate JavaScript.',
      prereqs: ['JavaScriptA'],
      start_date: '05/01/2022',
      end_date: '06/04/2022',
      start_time: '15:00:00',
      end_time: '16:00:00',
      location: 'https://zoom.us/my/john321',
      price: 1200,
    },
    {
      schedule_id: 3,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test008',
      size: 12,
      subject: 'Intro to CSS',
      description: 'Welcome to CSS!',
      prereqs: ['Html'],
      start_date: '09/01/2022',
      end_date: '10/04/2022',
      start_time: '15:30:00',
      end_time: '17:45:00',
      location: 'https://zoom.us/my/john321',
      price: 500,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test010',
      size: 15,
      subject: ' Intro JavaScript',
      description: 'Welcome to JavaScript!',
      prereqs: ['Html,css'],
      start_date: '11/19/2022',
      end_date: '12/10/2022',
      start_time: '15:45:00',
      end_time: '16:45:00',
      location: 'https://zoom.us/my/john321',
      price: 600,
    },
    {
      schedule_id: 1,
      course_id: 1,
      instructor_id: 1,
      instructor_name: 'Test003',
      size: 15,
      subject: 'CS101',
      description: 'Computer Science fundamentals',
      prereqs: [],
      start_date: '01/19/2022',
      end_date: '02/10/2022',
      start_time: '17:00:00',
      end_time: '18:00:00',
      location: 'https://zoom.us/my/john123',
      price: 1000,
    },
    {
      schedule_id: 3,
      course_id: 5,
      instructor_id: 10,
      instructor_name: 'Mark',
      size: 20,
      subject: 'Fundamental Python',
      description: 'Computer Science fundamentals',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '04/04/2022',
      end_date: '04/28/2022',
      start_time: '17:00:00',
      end_time: '18:00:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 5,
      course_id: 8,
      instructor_id: 80,
      instructor_name: 'Mark',
      size: 20,
      subject: 'App Building Fundamentals',
      description:
        'A month/long course where students with design, build, and deploy an app from beginning to end!',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '10/30/2022',
      end_date: '11/28/2022',
      start_time: '17:00:00',
      end_time: '18:00:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 5,
      course_id: 8,
      instructor_id: 80,
      instructor_name: 'Mark',
      size: 20,
      subject: 'App Building Fundamentals',
      description:
        'A month/long course where students with design, build, and deploy an app from beginning to end!',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '05/12/2022',
      end_date: '06/28/2022',
      start_time: '10:10:00',
      end_time: '11:15:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 0,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test009',
      size: 14,
      subject: 'Welcome to Python!',
      description: 'Please select a course!',
      prereqs: ['javascript,css,html'],
      start_date: '06/1/2022',
      end_date: '07/31/2022',
      start_time: '14:00:00',
      end_time: '15:00:00',
      location: 'https://zoom.us/my/haleyh',
      price: 500,
    },
    {
      schedule_id: 0,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test009',
      size: 14,
      subject: 'Welcome to Python!',
      description: 'Please select a course!',
      prereqs: ['javascript,css,html'],
      start_date: '01/13/2023',
      end_date: '02/24/202',
      start_time: '16:30:00',
      end_time: '17:40:00',
      location: 'https://zoom.us/my/haleyh',
      price: 500,
    },
    {
      schedule_id: 0,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test009',
      size: 14,
      subject: 'Welcome to Python!',
      description: 'Please select a course!',
      prereqs: ['javascript,css,html'],
      start_date: '11/07/2022',
      end_date: '11/06/2022',
      start_time: '11:00:00',
      end_time: '12:10:00',
      location: 'https://zoom.us/my/haleyh',
      price: 500,
    },
    {
      schedule_id: 0,
      course_id: 0,
      instructor_id: 2,
      instructor_name: 'Test013',
      size: 16,
      subject: 'Intro to HTML',
      description: 'Welcome to HTML!',
      prereqs: [''],
      start_date: '08/15/2022',
      end_date: '09/25/2022',
      start_time: '10:00:00',
      end_time: '11:00:00',
      location: 'https://zoom.us/my/tommy',
      price: 450,
    },
    {
      schedule_id: 0,
      course_id: 0,
      instructor_id: 2,
      instructor_name: 'Test013',
      size: 16,
      subject: 'Intro to HTML',
      description: 'Welcome to HTML!',
      prereqs: [''],
      start_date: '12/03/2022',
      end_date: '12/18/2022',
      start_time: '8:10:00',
      end_time: '9:10:00',
      location: 'https://zoom.us/my/tommy',
      price: 450,
    },
    {
      schedule_id: 0,
      course_id: 0,
      instructor_id: 2,
      instructor_name: 'Test013',
      size: 16,
      subject: 'Intro to HTML',
      description: 'Welcome to HTML!',
      prereqs: [''],
      start_date: '03/15/2022',
      end_date: '04/25/2022',
      start_time: '10:00:00',
      end_time: '11:00:00',
      location: 'https://zoom.us/my/tommy',
      price: 450,
    },
    {
      schedule_id: 0,
      course_id: 0,
      instructor_id: 2,
      instructor_name: 'Test013',
      size: 16,
      subject: 'Intro to HTML',
      description: 'Welcome to HTML!',
      prereqs: [''],
      start_date: '07/10/2022',
      end_date: '07/26/2022',
      start_time: '16:30:00',
      end_time: '17:30:00',
      location: 'https://zoom.us/my/tommy',
      price: 450,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test006',
      size: 16,
      subject: 'JavaScriptB',
      description: 'Intermediate JavaScript.',
      prereqs: ['JavaScriptA'],
      start_date: '06/16/2022',
      end_date: '07/20/2022',
      start_time: '9:00:00',
      end_time: '10:00:00',
      location: 'https://zoom.us/my/john321',
      price: 1200,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test006',
      size: 16,
      subject: 'JavaScriptB',
      description: 'Intermediate JavaScript.',
      prereqs: ['JavaScriptA'],
      start_date: '12/01/2022',
      end_date: '01/04/2023',
      start_time: '11:10:00',
      end_time: '12:10:00',
      location: 'https://zoom.us/my/john321',
      price: 1200,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test006',
      size: 16,
      subject: 'JavaScriptB',
      description: 'Intermediate JavaScript.',
      prereqs: ['JavaScriptA'],
      start_date: '03/10/2022',
      end_date: '06/15/2022',
      start_time: '15:30:00',
      end_time: '14:30:00',
      location: 'https://zoom.us/my/john321',
      price: 1200,
    },
    {
      schedule_id: 3,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test008',
      size: 12,
      subject: 'Intro to CSS',
      description: 'Welcome to CSS!',
      prereqs: ['Html'],
      start_date: '04/15/2022',
      end_date: '05/14/2022',
      start_time: '10:30:00',
      end_time: '11:45:00',
      location: 'https://zoom.us/my/john321',
      price: 500,
    },
    {
      schedule_id: 3,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test008',
      size: 12,
      subject: 'Intro to CSS',
      description: 'Welcome to CSS!',
      prereqs: ['Html'],
      start_date: '1/01/2022',
      end_date: '01/04/2023',
      start_time: '13:00:00',
      end_time: '14:00:00',
      location: 'https://zoom.us/my/john321',
      price: 500,
    },
    {
      schedule_id: 3,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test008',
      size: 12,
      subject: 'Intro to CSS',
      description: 'Welcome to CSS!',
      prereqs: ['Html'],
      start_date: '07/01/2022',
      end_date: '08/04/2022',
      start_time: '08:30:00',
      end_time: '09:45:00',
      location: 'https://zoom.us/my/john321',
      price: 500,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test010',
      size: 15,
      subject: ' Intro JavaScript',
      description: 'Welcome to JavaScript!',
      prereqs: ['Html,css'],
      start_date: '03/12/2022',
      end_date: '04/20/2022',
      start_time: '08:45:00',
      end_time: '09:45:00',
      location: 'https://zoom.us/my/john321',
      price: 600,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test010',
      size: 15,
      subject: ' Intro JavaScript',
      description: 'Welcome to JavaScript!',
      prereqs: ['Html,css'],
      start_date: '08/19/2022',
      end_date: '09/10/2022',
      start_time: '10:35:00',
      end_time: '11:35:00',
      location: 'https://zoom.us/my/john321',
      price: 600,
    },
    {
      schedule_id: 2,
      course_id: 3,
      instructor_id: 2,
      instructor_name: 'Test010',
      size: 15,
      subject: ' Intro JavaScript',
      description: 'Welcome to JavaScript!',
      prereqs: ['Html,css'],
      start_date: '10/14/2022',
      end_date: '11/13/2022',
      start_time: '14:15:00',
      end_time: '15:15:00',
      location: 'https://zoom.us/my/john321',
      price: 600,
    },
    {
      schedule_id: 1,
      course_id: 1,
      instructor_id: 1,
      instructor_name: 'Test003',
      size: 15,
      subject: 'CS101',
      description: 'Computer Science fundamentals',
      prereqs: [],
      start_date: '05/28/2022',
      end_date: '06/28/2022',
      start_time: '15:00:00',
      end_time: '16:00:00',
      location: 'https://zoom.us/my/john123',
      price: 1000,
    },
    {
      schedule_id: 1,
      course_id: 1,
      instructor_id: 1,
      instructor_name: 'Test003',
      size: 15,
      subject: 'CS101',
      description: 'Computer Science fundamentals',
      prereqs: [],
      start_date: '12/10/2022',
      end_date: '01/10/2023',
      start_time: '11:00:00',
      end_time: '12:00:00',
      location: 'https://zoom.us/my/john123',
      price: 1000,
    },

    {
      schedule_id: 3,
      course_id: 5,
      instructor_id: 10,
      instructor_name: 'Mark',
      size: 20,
      subject: 'Fundamental Python',
      description: 'Computer Science fundamentals',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '09/22/2022',
      end_date: '10/28/2022',
      start_time: '9:00:00',
      end_time: '10:00:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 3,
      course_id: 5,
      instructor_id: 10,
      instructor_name: 'Mark',
      size: 20,
      subject: 'Fundamental Python',
      description: 'Computer Science fundamentals',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '03/24/2022',
      end_date: '04/08/2022',
      start_time: '13:10:00',
      end_time: '14:15:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 3,
      course_id: 5,
      instructor_id: 10,
      instructor_name: 'Mark',
      size: 20,
      subject: 'Intro to React',
      description: 'Welcome to React',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '03/15/2022',
      end_date: '04/18/2022',
      start_time: '13:30:00',
      end_time: '14:45:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 3,
      course_id: 5,
      instructor_id: 10,
      instructor_name: 'Mark',
      size: 20,
      subject: 'Intro to React',
      description: 'Welcome to React',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '08/03/2022',
      end_date: '09/08/2022',
      start_time: '10:10:00',
      end_time: '11:15:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 3,
      course_id: 5,
      instructor_id: 10,
      instructor_name: 'Mark',
      size: 20,
      subject: 'Intro to React',
      description: 'Welcome to React',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '06/01/2023',
      end_date: '07/05/2023',
      start_time: '08:00:00',
      end_time: '09:05:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
    {
      schedule_id: 3,
      course_id: 5,
      instructor_id: 10,
      instructor_name: 'Mark',
      size: 20,
      subject: 'Intro to React',
      description: 'Welcome to React',
      prereqs: ['JavaScript', 'HTML', 'CSS'],
      start_date: '10/30/2022',
      end_date: '11/28/2022',
      start_time: '17:00:00',
      end_time: '18:00:00',
      location: 'https://zoom.us/my/john123',
      price: 500,
    },
  ],

  newsfeed: [],
};
