module.exports = {
  // Backgrounds
  '@header__bg': '#FEAD2A',
  '@header__bg--dark': '#263E47',
  '@footer__bg': '#6A0C49',

  '@body__bg': '#EEEDD9',
  '@body__bg--green': '#9FB222',
  '@body__bg--blue': '#096A70',
  '@body__bg--peach': '#FCDFAA',
  '@body__bg--concrete': '#F2F2F2',
  '@body__bg--white': '#FAF9F8',
  '@body__bg--yellow': '#F2CE60',
  '@badge-card__bg--white': ' #EDEED7',
  '@classroom__feedback__bg--clay': '#8D8950',
  '@il__bg--Allsports': '#1E6A70',
  '@il__bottom__leftCircle--cream-can': '#F2C35F',
  '@il__top__bottomContent--white': '#FFFFFF',
  '@iac__section__bg--snow': '#FBFBFB',
  '@badge-capital__bg--pattens-blue': '#DAF4FF',
  '@instuctor-calendar-style__bg--blue-lagoon': '#006C72',
  '@instructor-calendar-style__bg--white': '#FFFFFF',
  '@instructor-calendar-style__bg--white-smoke': '#F2F2F2',
  '@stat-icon-wrapper__bg--varden': '#FBECD1',
  '@landing-container__bg--blue-stone': '#156A70',
  '@news__bg--white': '#FFFFFF',
  '@parent-navbar__bg--white': '#FFFFFF',
  '@student-db__bg--teal': '#008080',
  '@teacher-db__bg--purple': '800080',
  'student-story-card__bg--white': '#FFFFFF',
  '@student-styles__bg--light-cyan': '#E0FFFF',
  '@calendar__bg--cream-can': '#F1C461',
  '@success-class-event__bg--robins-egg-blue': 'rgba(0, 202, 183, 0.25)',
  '@warning-class-event__bg--dark-tangerine': '#FAAD14',
  '@error-class-event__bg--salmon': '#FA8072',
  '@ant-picker__bg--varden': '#FBECD1',
  '@ant-menu__bg--supernova': '#FEAE28',
  '@header__bg--light-sea-green': '#21C5B5',
  '@header__bg--white': '#FFFFFF',

  // Buttons
  '@btn__bg--blue': '#21C5B5',
  '@btn__bg--white': '#EEEDD9',
  '@btn__bg--red': '#EC2C4E',
  '@btn__bg--maroon': '#6A0C49',
  '@btn__bg--yellow': '#F2CE60',
  '@btn__bg--orange': '#F66721',
  '@btn__bg__hover--golden-poppy': '#FDC312',
  '@btn__bg__peach': '#FCDFAA',
  '@insturctor-calendar-style__btn__bg--turquoise': '#34D4C5',
  '@btn__bg--safety-orange': '#F26602',
  '@landing__btn__bg--sunglow': '#FBC740',
  '@navbar__btn__bg--white': '#EDEED7',
  '@navbar__btn__bg--blue-lagoon': '#006C72',
  '@news__btn__bg--licorice': '#2E3646',
  '@news__btn__bg--black': '#000000',
  '@pl__na__top__btn__bg--amaranth': '#DF294A',
  '@pl__na__top_-btn_-bg--tyrian-purple': '#5D0B40',
  // Borders
  '@btn__border-radius': '6px',
  // Fonts
  '@text__font-family': "'Montserrat', sans-serif",
  '@text__font-family--header': "'Staatliches', cursive",

  '@text__font-size--h1': '2.375rem',
  '@text__font-size--h2': '1.875rem',
  '@text__font-size--h3': '1.5rem',
  '@text__font-size--h4': '1.25rem',
  '@text__font-size--h5': '1rem',
  '@text__font-size--body': '0.875rem',
  '@text__font-size--footer': '0.75rem',

  '@text__line-height--h1': '2.875rem',
  '@text__line-height--h2': '2.5rem',
  '@text__line-height--h3': '2rem',
  '@text__line-height--h4': '1.75rem',
  '@text__line-height--h5': '1.5rem',
  '@text__line-height--body': '1.375rem',
  '@text__line-height--footer': '1.25rem',

  '@text__color--maroon': '#3B0E2B',
  '@text__color--white': '#FFFFFF',
  '@text__color--black': '#232420',
  '@il__text__color--fiord': '#485b63',
  '@submitbtn__text__color--pumpkin': '#F27712',
  '@close-modal-btn__text__color--red': '#FF0000',
  '@banner-content__text__color--robins-egg-blue': '#00CAB7',
  '@errorMessage': '#F5222D',
  '@text__color--yellow': '#FFFF00',
  '@text__color--green': '#008000',
  '@navbar__text__color--white': '#EDEED7',
  '@navbar__text__color--blue-lagoon': '#006C72',
  '@news__text__color--white': '#FFFFFF',
  '@pl__na__text__color--Tarawera': '#263D47',
  '@pl__na__text__color--black': '#000000',
  '@top-right__text__color--grey': '#808080',
  '@text__color--pumpkin': '#F27712',
  '@calendar-modal__text__color--black': 'rgba(0, 0, 0, 0.65)',
  '@ant-menu__text__color--orange': '#FFA500',
  '@ant-menu__text__color--zambezi': '#595959',
  '@ant-menu__text__color--grey': '#808080',
  '@ant-menu__text__color--red': '#ff0000',
  '@ant-menu__text__color--tyrian-purple': 'rgba(116, 0, 73, 0.8)',
  '@header__text__color--teal': '#008080',

  // Focus Effects
  '@input__border--focus': '1px solid #21C5B5',
  '@input__box-shadow--focus': '0px 0px 10px 1px #21C5B5',
  '@input__transition--focus': '0.1s',
};
